services:
  postgres:
    container_name: postgres
    image: "postgres:17-alpine"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    volumes:
      - ./compose/postgres/data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False" # Run in Desktop Mode, no need to log in.
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False" # Disable master password prompt
      PGADMIN_DEFAULT_EMAIL: "admin@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_SERVER_JSON_FILE: "/servers/servers.json"
    ports:
      - "5050:80"
    volumes:
      - ./compose/pgadmin/data:/var/lib/pgadmin
      - ./compose/pgadmin/servers:/servers
    depends_on:
      - postgres
    user: "0" # Run as root to avoid permission issues with mounted volumes
